[package]
name = "interfaces"
description = "A Rust library for interacting with network interfaces"
version = "0.0.1"
authors = ["Andrew Dunham <andrew@du.nham.ca>"]
homepage = "https://github.com/andrew-d/interfaces-rs"
repository = "https://github.com/andrew-d/interfaces-rs"
documentation = "https://andrew-d.github.io/interfaces-rs/interfaces/index.html"
license = "MIT/Apache-2.0"
build = "build.rs"

[dependencies]
bitflags = "0.5"
ip = "1.1"
lazy_static = "0.2"
libc = "0.2"
nix = "0.5"

[build-dependencies]
gcc = "0.3"
handlebars = "0.16"
rustc-serialize = "0.3"
